#!/usr/bin/env bash
# Double the number of webservers

sudo apt-get -y update
sudo apt-get install -y nginx

# Add a custom HTTP response header
sudo sed -i "/server_name _/a add_header X-Served-By \$hostname;" /etc/nginx/sites-enabled/default

# Test Nginx configuration for syntax errors
sudo nginx -t

# Restart Nginx to apply changes
sudo service nginx restart
