#!/usr/bin/env bash
# a Bash script that configures a server to the above requirements

sudo rm /etc/nginx/sites-enabled/default

sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

sudo service nginx restart
