#!/usr/bin/env bash
# Your machine has an SSH configuration file for the local SSH client
# let’s configure it to our needs so that you can connect to a server without
# typing a password. Share your SSH client configuration in your answer file.

Host 231851-web-01
    HostName 34.229.72.200
    User ubuntu
    IdentityFile ~/.ssh/school
    PasswordAuthentication no
